apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: default
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 31883
